/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Government.LicenseDirectory;
import Business.Government.TrainingDirectory;
import Business.Organization.Organizations;
import Business.UserAccount.UserAccount;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import userinterface.SystemAdminWorkArea.LoginForm;

/**
 *
 * @author Mayan Mishra
 */
public class GovernmentWorkArea extends javax.swing.JPanel {

    ViewJPanel viewPanel;

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    EcoSystem ecosystem;
    LicenseDirectory licenseDir;
    TrainingDirectory trainingDir;
    JPanel userProcessContainer;
    UserAccount account;
    Organizations organization;
    Enterprise enterprise;

    /**
     * Creates new form GovernmentWorkArea
     */
    public GovernmentWorkArea(JPanel userProcessContainer, UserAccount account, Organizations organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.ecosystem = business;
        this.account = account;

        this.organization = organization;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GovernmentSplitPane = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCreateLicenseTraining = new javax.swing.JButton();
        btnViewLicenseTraining = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        GovernmentSplitPane.setDividerSize(1);
        GovernmentSplitPane.setPreferredSize(new java.awt.Dimension(141, 243));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(145, 243));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Government Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        btnCreateLicenseTraining.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateLicenseTraining.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreateLicenseTraining.setText("Create License/Training");
        btnCreateLicenseTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLicenseTrainingActionPerformed(evt);
            }
        });

        btnViewLicenseTraining.setBackground(new java.awt.Color(255, 255, 255));
        btnViewLicenseTraining.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewLicenseTraining.setText("View License/Training");
        btnViewLicenseTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLicenseTrainingActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateLicenseTraining, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewLicenseTraining, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addComponent(btnCreateLicenseTraining)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLicenseTraining)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(33, 33, 33))
        );

        GovernmentSplitPane.setLeftComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 780));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 780));
        jPanel1.setLayout(new java.awt.CardLayout());
        GovernmentSplitPane.setRightComponent(jPanel1);

        add(GovernmentSplitPane);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateLicenseTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLicenseTrainingActionPerformed
        // TODO add your handling code here:

        //        jPanel1.remove(manageHospital);
        //        jPanel1.add(manageUsers);
        //        CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
        //        cardLayout.next(jPanel1);
        GovernmentPanel createPanel = new GovernmentPanel(this.enterprise,this.ecosystem);
        GovernmentSplitPane.setRightComponent(createPanel);
    }//GEN-LAST:event_btnCreateLicenseTrainingActionPerformed

    private void btnViewLicenseTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLicenseTrainingActionPerformed
        // TODO add your handling code here:
        //        jPanel1.remove(manageUsers);
        //        jPanel1.add(manageHospital);
        //
        //        CardLayout cardLayout = (CardLayout) jPanel1.getLayout();
        //        cardLayout.next(jPanel1);

        ViewJPanel viewPanel = new ViewJPanel(this.enterprise,this.ecosystem);
        GovernmentSplitPane.setRightComponent(viewPanel);
    }//GEN-LAST:event_btnViewLicenseTrainingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        JFrame frame = (JFrame) SwingUtilities.getRoot(this);
        frame.remove(this);
        frame.pack();
        frame.setSize(1425, 988);
        frame.add(new LoginForm(ecosystem));
        dB4OUtil.storeSystem(EcoSystem.getInstance());
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane GovernmentSplitPane;
    private javax.swing.JButton btnCreateLicenseTraining;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewLicenseTraining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
